### ISSUE TITLE
Plugin uses invalid ServiceControl queue name

### ISSUE THREAD

**Issue by timbussmann** [Particular/ServiceControl.Plugin.Nsb6.SagaAudit#16]
### Symptoms

The SagaAudit plugin contains logic to determine the machine name for the ServiceControl queue if the ServiceControl queue isn't configured explicitly. The queue name which is passed down to the transport can therefore look like this Particular.ServiceControl@. This value is invalid for most transports other than MSMQ and will cause the plugin to fail (e.g. RabbitMQ).
The endpoint crashes.
### Who's Affected

Users that are running v1.

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceControl.Plugin.Nsb6.SagaAudit/commit/8057d12fd16497e28343da6b87114c95409ded88
