### ISSUE TITLE
Message data empty in saga audit

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl.Plugin.Nsb6.SagaAudit#18]
Raised in https://groups.google.com/forum/#!topic/particularsoftware/_uXaOg3FkLA by Leonard Riotto 

![2016-10-18 08_40_44-serviceinsight](https://cloud.githubusercontent.com/assets/174258/19589429/777a4186-976c-11e6-8a55-ebc689c21663.png)

Helpful information to include
Product name: ServiceInsight
Version: 1.5.7

When viewing the message information in the saga diagram (see attached screenshot), the message data is showing empty.  I have public properties which should be visible and I clicked on the Show Message Data button to display it.  Am I missing a setting or something that is keeping this information from showing up in the diagram?  I am using NSB6.SagaAudit v1.0.2.

**Comment by danielmarbach** [comment]
Maybe we need to move this issue to ServiceInsight or ServiceControl since the saga audit plugin is not collecting the message body but ServiceControl is. I raised it here since the user originally raised it in the context of SagaAudit.

**Comment by johnsimons** [comment]
@danielmarbach do you have the Servicecontrol version ?

**Comment by danielmarbach** [comment]
Not yet. Asked for the details in the GG group.
