### ISSUE TITLE
Perform a check to ensure Audit queue is enabled and configured

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceControl.Plugin.Nsb6.SagaAudit#22]
Currently there's no check and user could end up in a situation when there's no errors but things don't work either, e.g. message don't appear in SI.

Preferred behavior would be throwing an exception in SagaAudit plugin when at runtime it detects that audit queue is not configured.

Also need to check if the plugin is executed at all if the audit behavior is turned off.

**Comment by mikeminutillo** [comment]
There's a couple of ways we could approach this. 

1. We can make the SagaAudit feature depend on the Audit feature using the features subsystem. If we do that, and the user has not configured Audit, then the SagaAudit plugin won't start (silently)
2. We can check at startup if the Audit feature is enabled. If it is, great. If not, then what do we do? Do we log an error/warning? Do we throw an exception and stop the endpoint from starting?

**Comment by HEskandari** [comment]
Is it possible to do a WARN as a part of features subsystem, when the depending feature is disabled? I'd be surprised if that's not done already.

I'm happy with a WARN, no need to throw an exception but silently ignoring is not the best approach IMO.

**Comment by HEskandari** [comment]
Once this is done, we also need to update Particular/docs.particular.net#2423 to reflect the new behavior.
