### ISSUE TITLE
Bad ServiceControl.Plugin.Nsb6.SagaAudit 1.0.0-beta0001.nupkg pushed to NuGet

### ISSUE THREAD

**Issue by boblangley** [Particular/ServiceControl.Plugin.Nsb6.SagaAudit#4]
Octopus deploy caching allowed me to push a build with a known bug to NuGet.org. I am pushing a new build as Beta 2 to make sure the bug is resolved.

**Comment by boblangley** [comment]
@danielmarbach I told you it was something I did.

**Comment by boblangley** [comment]
Beta 2 has been pushed to Nuget

**Comment by danielmarbach** [comment]
:+1:
