### ISSUE TITLE
Beta 2 not compatible with Core beta 4

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl.Plugin.Nsb6.SagaAudit#8]
Beta 2 not compatible with Core beta 4

> Message: "Method not found: 'System.String 
> NServiceBus.SettingsExtentions.LocalAddress(NServiceBus.Settings.ReadOnlySettings)'."}
> Source: ServiceControl.Plugin.Nsb6.SagaAudit
> StackTrace: " at 
> ServiceControl.Plugin.ServiceControlBackend.<VerifyIfServiceControlQueueExists>d__7.MoveNext()
> at 
> System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& 
> stateMachine)"

**Comment by indualagarsamy** [comment]
@ramonsmits - Looks like the PR to do this update was merged. 
https://github.com/Particular/ServiceControl.Plugin.Nsb6.SagaAudit/pull/7
@SimonCropp @mikeminutillo - do we just need to merge to master and push to nuget?

**Comment by SimonCropp** [comment]
it is merge to the release branch. no need for it on master. i would assume the @Particular/servicecontrol-maintainers would release it

**Comment by mikeminutillo** [comment]
Beta3 released which is compatible with Core Beta4
